name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4
    - name: List schemes
      run: xcodebuild -project MetalGoose.xcodeproj -list
    - name: Build
      run: |
        xcodebuild -project MetalGoose.xcodeproj \
          -scheme MetalGoose \
          -configuration Debug \
          -derivedDataPath build \
          build
    - name: Upload app
      uses: actions/upload-artifact@v4
      with:
        name: MetalGoose
        path: build/Build/Products/Debug/MetalGoose.app
